ERROR_GENERIC = "Xatolik yuz berdi. Iltimos, birozdan keyin qayta urinib ko'ring."
WELCOME = (
    "👋 Salom, <b>{name}</b>!\n\n"
    "🎬 Bu bot orqali kinolarni tez va oson olishingiz mumkin.\n\n"
    "📌 <b>Qanday foydalaniladi?</b>\n"
    "🔢 Kino kodini yuboring, masalan: <code>1001</code>\n"
    "▶️ Bot sizga shu koddagi kinoni yuboradi\n"
    "📣 Agar obuna so'ralsa, kanallarga obuna bo'lib, <b>Obuna bo'ldim</b> tugmasini bosing\n\n"
    "✨ Endi kino kodini yuboring."
)
SEND_MOVIE_CODE = "🔢 Kino kodini yuboring."
MOVIE_NOT_FOUND = "❌ Bunday kodli kino topilmadi."
SUBSCRIBE_REQUIRED = "📣 Botdan foydalanish uchun quyidagi kanallarga obuna bo'ling:"
SUBSCRIBE_BUTTON = "✅ Obuna bo'ldim"
SUBSCRIBE_FAILED = "❌ Siz hali barcha kanallarga obuna bo'lmadingiz."
SUBSCRIBE_SUCCESS = "✅ Obuna tasdiqlandi.\n\n🔢 Kino kodini yuboring, masalan: <code>1001</code>"
ADMIN_DENIED = "Bu bo'lim faqat adminlar uchun."
ADMIN_PANEL = "🛠 Admin panel:"
CANCELLED = "Bekor qilindi."
SEND_VIDEO = "Kino videosini yuboring yoki forward qiling."
SEND_TITLE = "Kino nomini yuboring."
SEND_CAPTION = "Caption/izoh yuboring yoki o'tkazib yuboring."
SKIP = "O'tkazib yuborish"
MOVIE_ADDED = "✅ Kino muvaffaqiyatli qo'shildi. Kodi: {code}"
SEND_DELETE_CODE = "O'chiriladigan kino kodini yuboring."
MOVIE_DELETED = "✅ Kino o'chirildi."
CHANNEL_SEND = "Kanal username (@kanal) yoki ID yuboring."
CHANNEL_ADDED = "✅ Kanal qo'shildi."
CHANNEL_ADMIN_REQUIRED = "Bot ushbu kanalda admin bo'lishi kerak."
BROADCAST_SEND = "Yuboriladigan xabarni yuboring."
BROADCAST_CONFIRM = "Xabar barcha foydalanuvchilarga yuborilsinmi?"
BROADCAST_DONE = "✅ Yuborildi: {sent} ta, ❌ xato: {failed} ta"
SEND_ADMIN_ID = "Admin Telegram ID raqamini yuboring."
ADMIN_ADDED = "✅ Admin qo'shildi."
ADMIN_REMOVED = "✅ Admin olib tashlandi."
SUPER_ADMIN_ONLY = "Bu amal faqat super-admin uchun."
SEND_MAIN_CHANNEL = "Asosiy kanal ID yoki username yuboring."
MAIN_CHANNEL_SAVED = "✅ Asosiy kanal saqlandi."
SEND_SPONSOR_TEXT = "Sponsor xabarini yuboring."
SPONSOR_TEXT_SAVED = "✅ Sponsor matni saqlandi."
INVALID_ID = "To'g'ri Telegram ID raqam yuboring."
USER_BLOCKED = "Siz botdan foydalana olmaysiz."
